spring.config.import=file:env.properties
spring.application.name=skillbridge-backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JWT Properties
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true